image:
  file: .gitpod.Dockerfile
tasks:
  - name: Starting Project
    init:  composer create-project laravel/laravel:^8.0 laravel &&
      mkdir -p laravel/packages/badaso/core && 
      mv {,.}* laravel/packages/badaso/core 2>/dev/null; true &&
      cd laravel &&
      cp .env.example .env &&
      sed -i "s|APP_URL=|APP_URL=${GITPOD_WORKSPACE_URL}|g" .env &&
      sed -i "s|APP_URL=https://|APP_URL=https://8000-|g" .env &&
      composer install &&
      php artisan key:generate
    command: mysql -u root -e "create database laravel" &&
      php artisan storage:link &&
      npm install &&
      php artisan migrate &&
      php artisan serve
ports:
  - port: 8000
    onOpen: open-browser
  - port: 3306
    onOpen: ignore
vscode:
  extensions:
    - bmewburn.vscode-intelephense-client
    - MehediDracula.php-namespace-resolver
    - junstyle.php-cs-fixer