name: Tests

on:
  push:
    branches:
      - 'master'
  pull_request:
    types:
      - synchronize
      - opened
      - edited
      - reopened

jobs:
  test:
    runs-on: ubuntu-latest
    
    strategy:
      fail-fast: false
      matrix:
        php: [8.0, 8.1]
        laravel: ['8.*']
        laravel-require: [8.0]
        mysql-version: [8.0]

    name: 'PHP ${{ matrix.php }} / Laravel ${{ matrix.laravel }}'

    steps:
      - uses: actions/checkout@master
      
      # Configure Mysql
      - name: Mysql setup
        uses: ankane/setup-mysql@v1
        with:
          mysql-version: ${{ matrix.mysql-version }}
          database: laravel

      # Configure PHP
      - name: Select PHP version
        uses: shivammathur/setup-php@master
        with:
          php-version: '${{ matrix.php }}'
          extensions: mbstring, pdo_sqlite, fileinfo, gd
          coverage: none

      # Install legacy factories for Laravel 8/9
      - name: Install legacy factories for Laravel
        run: composer create-project laravel/laravel:^${{matrix.laravel-require}} laravel

      # Display installed laravel version
      - name: Show laravel version
        run: cd laravel && 
          composer show laravel/framework

#       # Laravel configuration
#       - name: Laravel file configuration
#         run: cd laravel && 
#           touch database/database.sqlite &&
#           sed -i 's/DB_CONNECTION=mysql/DB_CONNECTION=sqlite/g' .env &&
#           sed -i 's/DB_DATABASE=laravel/DB_DATABASE=database\/database.sqlite/g' .env
          
      # Laravel require badaso core
      - name: Laravel file configuration
        run: git branch &&
          cd laravel &&
          composer require badaso/core:dev-${GITHUB_HEAD_REF} &&
          composer update --no-interaction && 
      
      # Laravel setup
      - name: Laravel setup 
        run: cd laravel &&
          php artisan badaso:setup --force &&
          php artisan badaso-test:setup &&
          php artisan db:wipe && 
          php artisan migrate && 
          php artisan db:seed --class="Database\Seeders\Badaso\BadasoSeeder"
          
      # Badaso core test
      - name: Badaso core test
        run: cd laravel && php artisan test


